---

- name: disable Ceph Repository
  ini_file:
    path: /etc/yum.repos.d/CentOS-Ceph-Octopus.repo
    section: centos-ceph-octopus
    option: enabled
    value: '0'


- name: disable Docker Repository
  ini_file:
    path: /etc/yum.repos.d/docker-ce.repo
    section: docker-ce-stable
    option: enabled
    value: '0'


- name: disable Kubernetes Repository
  ini_file:
    path: /etc/yum.repos.d/Kubernetes.repo
    section: Kubernetes
    option: enabled
    value: '0'


- name: disable Ansible Repository
  ini_file:
    path: /etc/yum.repos.d/CentOS-SIG-ansible-29.repo
    section: centos-ansible-29
    option: enabled
    value: '0'

