---
- name: restart_keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes

- name: restart_docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: restart_ceph_mgr
  shell: ceph mgr module disable dashboard && ceph mgr module enable dashboard

